# Generated by Django 5.1.1 on 2024-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0002_cs_dep_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='cs_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
            ],
        ),
    ]
