# Generated by Django 5.1.1 on 2024-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0003_cs_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cs_mark',
        ),
        migrations.AddField(
            model_name='cs_dep',
            name='sub1',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cs_dep',
            name='sub2',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cs_dep',
            name='sub3',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cs_dep',
            name='sub4',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cs_dep',
            name='sub5',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
