# Generated by Django 5.1.1 on 2024-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0004_delete_cs_mark_cs_dep_sub1_cs_dep_sub2_cs_dep_sub3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_dep',
            name='sub1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cs_dep',
            name='sub2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cs_dep',
            name='sub3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cs_dep',
            name='sub4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cs_dep',
            name='sub5',
            field=models.IntegerField(),
        ),
    ]
