# Generated by Django 5.1.1 on 2024-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0005_alter_cs_dep_sub1_alter_cs_dep_sub2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='csdep_sem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('stuclass', models.CharField(max_length=100)),
                ('sub6', models.IntegerField()),
                ('sub7', models.IntegerField()),
                ('sub8', models.IntegerField()),
                ('sub9', models.IntegerField()),
                ('sub10', models.IntegerField()),
            ],
        ),
    ]
