# Generated by Django 5.1.1 on 2024-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0006_csdep_sem2'),
    ]

    operations = [
        migrations.CreateModel(
            name='csdep_sem3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('stuclass', models.CharField(max_length=100)),
                ('sub11', models.IntegerField()),
                ('sub12', models.IntegerField()),
                ('sub13', models.IntegerField()),
                ('sub14', models.IntegerField()),
                ('sub15', models.IntegerField()),
            ],
        ),
    ]
