# Generated by Django 5.1.1 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0007_csdep_sem3'),
    ]

    operations = [
        migrations.CreateModel(
            name='csdep_sem4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('stuclass', models.CharField(max_length=100)),
                ('sub16', models.IntegerField()),
                ('sub17', models.IntegerField()),
                ('sub18', models.IntegerField()),
                ('sub19', models.IntegerField()),
                ('sub20', models.IntegerField()),
            ],
        ),
    ]
