# Generated by Django 5.1.1 on 2024-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumarkapp', '0008_csdep_sem4'),
    ]

    operations = [
        migrations.CreateModel(
            name='csdep_sem5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('stuclass', models.CharField(max_length=100)),
                ('sub21', models.IntegerField()),
                ('sub22', models.IntegerField()),
                ('sub23', models.IntegerField()),
                ('sub24', models.IntegerField()),
                ('sub25', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='csdep_sem6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('stuclass', models.CharField(max_length=100)),
                ('sub26', models.IntegerField()),
                ('sub27', models.IntegerField()),
                ('sub28', models.IntegerField()),
                ('sub29', models.IntegerField()),
                ('sub30', models.IntegerField()),
            ],
        ),
    ]
